
INSERT INTO `uni_department` (`faculty_id`, `department_name`) VALUES
  (155, 'Bilgisayar Bilimi ve Mühendisliği'),
  (155, 'Elektronik Mühendisliği'),
  (155, 'Endüstri Mühendisliği'),
  (155, 'Üretim Mühendisliği'),
  (155, 'Malzeme Bilimi ve Nanomühendislik'),
  (155, 'Mekatronik Mühendisliği'),
  (155, 'Moleküler Biyoloji, Genetik ve Biyomühendislik'),
  (156, 'Ekonomi'),
  (156, 'Görsel Sanatlar ve Görsel İletişim Tasarımı'),
  (156, 'Kültürel Çalışmalar'),
  (156, 'Toplumsal ve Siyasi Bilimler'),
  (157, 'Yönetim Bilimleri'),
  (158, 'Halkla İlişkiler ve Tanıtım(Lisans)'),
  (158, 'Sosyal Hizet(Lisans)'),
  (158, 'İşletme(Lisans)'),
  (158, 'Sosyoloji(Lisans)'),
  (158, 'Acil Durum ve Afet Yönetimi (Ön Lisans)'),
  (158, 'Adalet(Ön Lisans)'),
  (158, 'Bilgi Yönetimi (Ön Lisans)'),
  (158, 'Bankacılık ve Sigortacılık (Ön Lisans)'),
  (158, 'Bilgisayar Programcılığı (Ön Lisans)'),
  (158, 'Büro Yönetimi ve Yönetici Asistanlığı (Ön Lisans)'),
  (158, 'Çağrı Merkezi Hizmetleri (Ön Lisans)'),
  (158, 'Çocuk Gelişimi (Ön Lisans)'),
  (158, 'Dış Ticaret (Ön Lisans)'),
  (158, 'Emlak ve Emlak Yönetimi (Ön Lisans)'),
  (158, 'Halkla İlişkiler Ve Tanıtım (Ön Lisans)'),
  (158, 'İlahiyat (Ön Lisans)'),
  (158, 'İşletme Yönetimi (Ön Lisans)'),
  (158, 'İş Sağlığı ve Güvenliği (Ön Lisans)'),
  (158, 'Lojistik (Ön Lisans)'),
  (158, 'Reklamcılık (Ön Lisans)'),
  (158, 'Özek Güvenlik ve Koruma (Ön Lisans)'),
  (158, 'Sağlık Kurumları İşletmeciliği (Ön Lisans)'),
  (158, 'Sivil Hava Ulaştırma İşletmeciliği (Ön Lisans)'),
  (158, 'Sosyal Hizmet (Ön Lisans)'),
  (158, 'Tıbbi Dokümantasyon ve Sekreterlik (Ön Lisans)'),
  (158, 'Turizm ve Otel İşletmeciliği (Ön Lisans)'),
  (159, 'Klinik Diş Hekimliği'),
  (160, 'Eczacılık Meslek Bilimleri Bölümü(Anabilim Dalı)'),
  (160, 'Eczacılık Teknolojisi Bölümü'),
  (160, 'Temel Eczacılık Bilimleri Bölümü'),
  (161, 'Alman Dili ve Edebiyatı'),
  (161, 'Amerikan Kültürü ve Edebiyatı'),
  (161, 'Arap Dili ve Edebiyatı'),
  (161, 'Arkeoloji'),
  (161, 'Bilgi ve Belge Yönetimi'),
  (161, 'Coğrafya'),
  (161, 'Çağdaş Türk Lehçeleri ve Edebiyatları'),
  (161, 'Fars Dili ve Edebiyatı'),
  (161, 'Felsefe'),
  (161, 'Fransız Dili ve Edebiyatı'),
  (161, 'İngiliz Dili ve Edebiyatı'),
  (161, 'Psikoloji'),
  (161, 'Rus Dili ve Edebiyatı'),
  (161, 'Sanat Tarihi'),
  (161, 'Sosyoloji'),
  (161, 'Tarih'),
  (161, 'Türk Dili ve Edebiyatı'),
  (162, 'Aktüerya Bilimleri'),
  (162, 'Astronomi ve Astrofizik'),
  (162, 'Biyoloji'),
  (162, 'Fizik'),
  (162, 'Kimya'),
  (162, 'Matematik'),
  (162, 'Moleküler Biyoloji ve Genetik'),
  (163, 'Fotoğraf Bölümü'),
  (163, 'Geleneksel Türk El Sanatları'),
  (163, 'Grafik Bölümü'),
  (163, 'Heykel Bölümü'),
  (163, 'Müzik Bilimleri Bölümü'),
  (163, 'Resim Bölümü'),
  (163, 'Sahne Sanatları Bölümü'),
  (163, 'Seramik Bölümü'),
  (163, 'Sinema- TV Bölümü'),
  (163, 'Tekstil ve Moda Tasarımı'),
  (163, 'Temel Eğitimi Bölümü'),
  (164, 'Kamu Hukuku'),
  (164, 'Özel Hukuk Bölümü'),
  (165, 'Çalışma Ekonomisi ve Endüstri İlişkileri Bölümü'),
  (165, 'İktisat Bölümü'),
  (165, 'Ekonometri Bölümü'),
  (165, 'İşletme Bölümü'),
  (165, 'Kamu Yönetimi Bölümü'),
  (165, 'Sosyal Hizmet Bölümü'),
  (165, 'Uluslararası İlişkiler Bölümü'),
  (165, 'Uluslararası Ticaret ve Lojistik Bölümü'),
  (165, 'Yönetim Bilişim Sistemleri Bölümü'),
  (166, 'Felsefe ve Din Bilimleri Bölümü'),
  (166, 'İlköğretim Din Kültürü ve Ahlak Bilgisi Eğitimi Bölümü'),
  (166, 'İslam Tarihi ve Sanatları Bölümü'),
  (166, 'Temel İslam Bilimleri Bölümü'),
  (167, 'Gazetecilik Bölümü'),
  (167, 'Halkla İlişkiler ve Tanıtım Bölümü'),
  (167, 'Radyo-Televizyon ve Sinema Bölümü'),
  (168, 'Beden Eğitimi ve Spor Bölümü'),
  (168, 'Bilgisayar ve Öğretim Teknolojileri Eğitimi Bölümü'),
  (168, 'Eğitim Bilimleri Bölümü'),
  (168, 'Güzel Sanatlar Eğitimi Bölümü'),
  (168, 'İlk Öğretim Bölümü'),
  (168, 'Orta Öğretim Fen ve Matematik Alanları Eğitimi Bölümü'),
  (168, 'Orta Öğretim Sosyal Alanlar Eğitimi Bölümü'),
  (168, 'Özel Eğitim Bölümü'),
  (168, 'Türkçe Eğitimi Bölümü'),
  (168, 'Yabancı Diller Eğitimi Bölümü'),
  (169, 'İç Mimarlık Bölümü'),
  (169, 'Mimarlık Bölümü'),
  (169, 'Peyzaj Mimarlığı Bölümü'),
  (169, 'Şehir ve Bölge Planlama Bölümü'),
  (170, 'Bilgisayar Mühendisliği'),
  (170, 'Biyomedikal Mühendisliği'),
  (170, 'Çevre Mühendisliği'),
  (170, 'Elektrik - Elektronik Mühendisliği'),
  (170, 'Endüstri Mühendisliği'),
  (170, 'Enerji Sistemleri Mühendisliği'),
  (170, 'İnşaat Mühendisliği'),
  (170, 'Kimya Mühendisliği'),
  (170, 'Makine Mühendisliği'),
  (170, 'Mekatronik Mühendisliği'),
  (170, 'Metalurji ve Malzeme Mühendisliği'),
  (171, 'Bankacılık ve Finans Bölümü'),
  (171, 'İşletme'),
  (171, 'Maliye Bölümü'),
  (171, 'Sosyal Hizmet Bölümü'),
  (172, 'Harita Mühendisliği'),
  (172, 'Jeofizik Mühendisliği'),
  (172, 'Jeoloji Mühendisliği'),
  (172, 'Maden Mühendisliği'),
  (172, 'Petrol ve Doğal Gaz Mühendisliği'),
  (173, 'Beslenme ve Diyetetik'),
  (173, 'Çocuk Gelişimi'),
  (173, 'Ebelik'),
  (173, 'Fizyoterapi ve Rehabilitasyon'),
  (173, 'Hemşirelik'),
  (174, 'Antrenörlük Eğitimi Bölümü'),
  (174, 'Beden Eğitimi ve Spor Öğretmenliği Bölümü'),
  (174, 'Rekreasyon Bölümü'),
  (174, 'Spor Yöneticiliği Bölümü'),
  (175, 'Su Ürünleri Avlama ve İşleme Teknolojisi Bölümü'),
  (176, 'Cerrahi Tıp Bilimleri'),
  (176, 'Dahili Tıp Bilimleri'),
  (176, 'Temel Tıp Bilimleri'),
  (177, 'Gastronomi ve Mutfak Sanatları'),
  (177, 'Rekreasyon Yönetimi'),
  (177, 'Turizm İşletmeciliği'),
  (177, 'Turizm Rehberliği'),
  (178, 'Gıda Hijyeni ve Teknolojisi Bölümü'),
  (178, 'Klinik Bilimler Bölümü'),
  (178, 'Veteriner Hekimliği Temel Bilimler Bölümü'),
  (178, 'Zootekni ve Hayvan Besleme Bölümü'),
  (178, 'Klinik Öncesi Bilimler Bölümü'),
  (179, 'Bahçe Bitkileri Bölümü'),
  (179, 'Bitki Koruma Bölümü'),
  (179, 'Gıda Mühendisliği Bölümü'),
  (179, 'Tarım Ekonomisi Bölümü'),
  (179, 'Tarım Makinaları ve Teknolojileri Mühendisliği Bölümü'),
  (179, 'Tarımsal Biyoteknoloji Bölümü'),
  (180, 'Harita ve Kadastro Programı'),
  (180, 'Mimari Restorasyon Programı'),
  (180, 'Yapı Yalıtım Teknolojisi Programı'),
  (180, 'Yapı Denetim Programı'),
  (180, 'İnşaat Teknolojisi Programı'),
  (181, 'Bahçe Bitkileri'),
  (181, 'Bitki Koruma'),
  (181, 'Biyosistem Mühendisliği'),
  (181, 'Tarımsal Biyoteknoloji'),
  (181, 'Tarla Bitkileri'),
  (181, 'Zootekni'),
  (182, 'Diş Hekimliği'),
  (183, 'Eczacılık '),
  (184, 'Felsefe'),
  (184, 'İngiliz Dili ve Edebiyatı'),
  (184, 'Kafkas Dilleri ve Kültürü'),
  (184, 'Rus Dili ve Edebiyatı'),
  (184, 'Sanat Tarihi'),
  (184, 'Sosyoloji '),
  (184, 'Tarih'),
  (184, 'Türk Dili ve Edebiyatı'),
  (184, 'Türk Halk Bilimi'),
  (184, 'Çağdaş Türk Lehçeleri ve Edebiyatları'),
  (184, 'Doğu Dilleri ve Edebiyatı'),
  (185, 'Sınıf Öğretmenliği'),
  (185, 'Sosyal Bilgiler Öğretmenliği'),
  (185, 'Fen Bilgisi Öğretmenliği'),
  (185, 'İlköğretim Matematik Öğretmenliği'),
  (185, 'Rehberlik ve Psikolojik Danışmanlık'),
  (185, 'Almanca Öğretmenliği'),
  (185, 'İngilizce Öğretmenliği'),
  (186, 'Astronomi ve Uzay Bilimleri'),
  (186, 'Biyoloji'),
  (186, 'Fizik'),
  (186, 'Kimya '),
  (186, 'Matematik'),
  (187, 'Heykel Bölümü'),
  (187, 'Resim Bölümü'),
  (187, 'Geleneksel Türk Sanatları Bölümü'),
  (187, 'Görsel İletişim Tasarım Bölümü'),
  (187, 'Seramik ve Cam Tasarımı Bölümü'),
  (187, 'Temel Eğitim Bilimleri Bölümü'),
  (188, 'Uçak Mühendisliği'),
  (188, 'Uzay Mühendisliği'),
  (189, 'Hukuk'),
  (190, 'İktisat'),
  (190, 'İktisat(İÖ)'),
  (190, 'İşletme'),
  (190, 'İşletme(İÖ)'),
  (190, 'Maliye'),
  (190, 'Maliye(İÖ)'),
  (190, 'Siyaset Bilimi ve Kamu Yönetimi'),
  (190, 'Uluslararası İlişkiler'),
  (191, 'Temel İslam Bilimleri Bölümü'),
  (191, 'Felsefe ve Din Bilimleri Bölümü'),
  (191, 'İslam Tarihi ve Sanatları Bölümü'),
  (191, 'İlköğretim Din Kültürü Ahlak Bilgisi'),
  (192, 'Gazetecilik'),
  (192, 'Halkla İlişkiler ve Tanıtım'),
  (192, 'Radyo, Televizyon ve Sinema'),
  (193, 'Mimarlık'),
  (193, 'Şehir ve Bölge Planlama'),
  (194, 'Bilgisayar Mühendisliği'),
  (194, 'Biyomedikal Mühendisliği'),
  (194, 'Çevre Mühendisliği'),
  (194, 'Elektrik Elektronik Mühendisliği'),
  (194, 'Endüstri Mühendisliği'),
  (194, 'Endüstriyel Tasarım Mühendisliği'),
  (194, 'Enerji Sistemleri Mühendisliği'),
  (194, 'Gıda Mühendisliği'),
  (194, 'Harita Mühendisliği'),
  (194, 'İnşaat Mühendisliği'),
  (194, 'Makine Mühendisliği'),
  (194, 'Malzeme Bilimi ve Mühendisliği'),
  (194, 'Mekatronik Mühendisliği'),
  (194, 'Tekstil Mühendisliği'),
  (195, 'Beslenme ve Diyetetik'),
  (195, 'Ebelik'),
  (195, 'Hemşirelik'),
  (196, 'Tıp'),
  (197, 'Turizm İşletmeciliği'),
  (197, 'Turizm Rehberliği'),
  (197, 'Gastronomi ve Mutfak Sanatları'),
  (198, 'Temel Bilimler Bölümü'),
  (198, 'Klinik Öncesi Bilimler Bölümü'),
  (198, 'Klinik Bilimleri Bölümü'),
  (198, 'Zootekni ve Hayvan Besleme Bölümü'),
  (198, 'Gıda Hijyeni ve Teknolojisi Bölümü'),
  (199, 'Bilgisayar Mühendisliği Bölümü'),
  (199, 'Elektrik ve Elektronik Mühendisliği Bölümü'),
  (199, 'Endüstri Mühendisliği Bölümü'),
  (199, 'İnşaat Mühendisliği Bölümü'),
  (199, 'Kimya Mühendisliği Bölümü'),
  (199, 'Makina Mühendisliği Bölümü'),
  (200, 'Ekonomi Bölümü'),
  (200, 'İşletme Bölümü'),
  (200, 'Siyaset Bilimi ve Uluslararası İlişkiler Bölümü'),
  (201, 'Batı Dilleri ve Edebiyatları Bölümü'),
  (201, 'Çeviribilim Bölümü'),
  (201, 'Dilbilim Bölümü'),
  (201, 'Felsefe Bölümü'),
  (201, 'Fizik Bölümü'),
  (201, 'Kimya Bölümü'),
  (201, 'Matematik Bölümü'),
  (201, 'Moleküler Biyoloji ve Genetik Bölümü'),
  (201, 'Psikoloji Bölümü'),
  (201, 'Sosyoloji Bölümü'),
  (201, 'Tarih Bölümü'),
  (201, 'Türk Dili ve Edebiyatı Bölümü'),
  (202, 'İleri İngilizce Birimi'),
  (202, 'İngilizce Hazırlık Birimi'),
  (202, 'Modern Diller Birimi'),
  (203, 'Bilgisayar ve Öğretim Teknolojileri Eğitimi Bölümü'),
  (203, 'Eğitim Bilimleri Bölümü'),
  (203, 'İlköğretim Bölümü'),
  (203, 'Orta Öğretim Fen ve Matematik Alanları Eğitimi Bölümü'),
  (203, 'Yabancı Diller Eğitimi Bölümü'),
  (205, 'Turizm İşletmeciliği Bölümü'),
  (205, 'Uluslararası Ticaret Bölümü'),
  (205, 'Yönetim Bilişim Sistemleri Bölümü'),
  (209, 'Diş Hekimliği'),
  (210, 'Alman Dili ve Edebiyatı'),
  (210, 'Arap Dili ve Edebiyatı'),
  (210, 'Arkeoloji'),
  (210, 'Fars Dili ve Edebiyatı'),
  (210, 'Felsefe'),
  (210, 'Fransız Dili ve Edebiyatı'),
  (210, 'İngiliz Dili ve Edebiyatı'),
  (210, 'Japon Dili ve Edebiyatı'),
  (210, 'Karşılaştırmalı Edebiyat'),
  (210, 'Kültür Varlıklarını Koruma ve Onarım'),
  (210, 'Psikoloji'),
  (210, 'Rus Dili ve Edebiyatı'),
  (210, 'Sanat Tarihi'),
  (210, 'Sosyoloji'),
  (210, 'Tarih'),
  (210, 'Türk Dili ve Edebiyatı'),
  (210, 'Urdu Dili ve Edebiyatı'),
  (211, 'Aktüerya'),
  (211, 'Biyokimya'),
  (211, 'Biyoloji'),
  (211, 'Biyoteknoloji'),
  (211, 'Fizik'),
  (211, 'İstatistik'),
  (211, 'Kimya'),
  (211, 'Matematik'),
  (212, 'Endüstri Ürünleri Tasarımı'),
  (212, 'Fotoğraf'),
  (212, 'Geleneksel Türk Sanatları'),
  (212, 'Grafik'),
  (212, 'Heykel'),
  (212, 'İç Mimarlık ve Çevre Tasarımı'),
  (212, 'Resim'),
  (212, 'Seramik'),
  (213, 'Hukuk'),
  (214, 'İktisat'),
  (214, 'İşletme'),
  (214, 'Kamu Yönetimi'),
  (214, 'Uluslararası İlişkiler'),
  (214, 'Uluslararası Ticaret'),
  (215, 'Gazetecilik'),
  (215, 'Halkla İlişkiler ve Tanıtım'),
  (215, 'Radyo- Televizyon ve Sinema'),
  (215, 'Reklamcılık'),
  (216, 'Çocuk Gelişimi ve Ev Yönetimi Eğitimi'),
  (216, 'Eğitim Bilimleri'),
  (216, 'El Sanatları Eğitimi'),
  (216, 'Giyim Endüstrisi ve Giyim Sanatları Eğitimi'),
  (216, 'Uygulamalı Sanatlar Eğitimi'),
  (217, 'Bilgisayar Mühendisliği'),
  (217, 'Çevre Mühendisliği'),
  (217, 'Elektrik Elektronik Mühendisliği'),
  (217, 'Endüstri Mühendisliği'),
  (217, 'Harita Mühendisliği'),
  (217, 'İnşaat Mühendisliği'),
  (217, 'Jeoloji Mühendisliği'),
  (217, 'Kimya Mühendisliği'),
  (217, 'Maden Mühendisliği'),
  (217, 'Makine Mühendisliği'),
  (217, 'Metalurji ve Malzeme Mühendisliği'),
  (218, 'Mimarlık'),
  (218, 'Şehir ve Bölge Planlama'),
  (219, 'Beslenme ve Diyetetik'),
  (219, 'Çocuk Gelişimi'),
  (219, 'Ebelik'),
  (219, 'Hemşirelik'),
  (219, 'Sağlık Yönetimi'),
  (219, 'Sosyal Hizmet'),
  (220, 'Tıp'),
  (221, 'Eğitim'),
  (221, 'Elektronik ve Bilgisayar Eğitimi'),
  (221, 'Makina Eğitimi'),
  (222, 'Veterinerlik'),
  (223, 'Bahçe Bitkileri'),
  (223, 'Bitki Koruma'),
  (223, 'Gıda Mühendisliği'),
  (223, 'Peyzaj Mimarlığı'),
  (223, 'Tarım Ekonomisi'),
  (223, 'Tarım Makinaları ve Teknolojileri Mühendisliği'),
  (223, 'Tarımsal Yapılar ve Sulama'),
  (223, 'Tarla Bitkileri'),
  (223, 'Toprak Bilimi ve Bitki Besleme'),
  (223, 'Zootekni'),
  (224, 'Ayakkabı Tasarımı ve Üretimi'),
  (224, 'El Sanatları Tasarımı ve Üretimi'),
  (224, 'Moda Tasarımı'),
  (224, 'Seramik Tasarımı'),
  (224, 'Tekstil Tasarımı ve Üretimi'),
  (225, 'Bilgisayar Mühendisliği'),
  (225, 'Biyomedikal Mühendisliği'),
  (225, 'Elektrik Elektronik Mühendisliği'),
  (225, 'İmalat Mühendisliği'),
  (225, 'Makine Mühendisliği'),
  (225, 'Mekatronik Mühendisliği'),
  (225, 'Metalurji ve Malzeme Mühendisliği'),
  (226, 'Gastronomi ve Mutfak Sanatları'),
  (226, 'Rekreasyon Yönetimi'),
  (226, 'Seyahat İşletmeciliği'),
  (226, 'Seyahat İşletmeciliği ve Turizm Rehberliği'),
  (226, 'Turizm İşletmeciliği'),
  (227, 'Tıp'),
  (228, 'Diş Hekimliği'),
  (231, 'Canlandırma Film'),
  (231, 'Endüstri Ürünleri Tasarımı'),
  (231, 'Fotoğraf'),
  (231, 'Geleneksel Türk Sanatları'),
  (231, 'Grafik'),
  (231, 'Heykel'),
  (231, 'İç Mimarlık'),
  (231, 'Müzik'),
  (231, 'Resim'),
  (231, 'Seramik ve Cam'),
  (231, 'Film Tasarımı'),
  (231, 'Tekstil '),
  (231, 'Temel Eğitim'),
  (232, 'Gazetecilik'),
  (232, 'Halkla İlişkiler ve Tanıtım'),
  (232, 'Radyo Televizyon ve Sinema'),
  (233, 'Anestezi'),
  (233, 'Diş Protez Teknolojisi'),
  (233, 'İlk ve Acil Yardım'),
  (233, 'Patoloji Laboratuvar Teknikleri'),
  (233, 'Tıbbi Görüntüleme Teknikleri'),
  (233, 'Tıbbi Laboratuvar Teknikleri'),
  (234, 'Siyaset Bilimi ve Uluslararası İlişkiler (İngilizce)'),
  (234, 'Siyaset Bilimi ve Uluslararası İlişkiler '),
  (234, 'Kamu Yönetimi'),
  (234, 'Kamu Yönetimi (Fransızca)'),
  (234, 'Yerel Yönetimler'),
  (235, 'Antrenörlük Eğitimi'),
  (235, 'Beden Eğitimi ve Spor Öğretmenliği'),
  (235, 'Spor Yöneticiliği'),
  (236, 'Bankacılık ve Sigortacılık'),
  (236, 'Bankacılık ve Sigortacılık (İÖ)'),
  (236, 'Büro Yönetimi ve Yönetici Asistanlığı'),
  (236, 'Büro Yönetimi ve Yönetici Asistanlığı (İÖ)'),
  (236, 'Dış Ticaret'),
  (236, 'Dış Ticaret (İÖ)'),
  (236, 'Dış Ticaret (Uzaktan Öğretim)'),
  (236, 'Muhasebe ve Vergi Uygulamaları'),
  (236, 'Muhasebe ve Vergi Uygulamaları (İÖ)'),
  (236, 'Muhasebe ve Vergi Uygulamaları (Uzaktan Öğretim)'),
  (236, 'Pazarlama'),
  (236, 'Pazarlama (İÖ)'),
  (236, 'Pazarlama (Uzaktan Öğretim)'),
  (236, 'Turizm Rehberliği'),
  (236, 'Turizm ve Otel İşletmeciliği'),
  (236, 'Turizm ve Otel İşletmeciliği (İÖ)'),
  (236, 'Turizm ve Seyahat Hizmetleri'),
  (236, 'Yerel Yönetimler'),
  (237, 'Fizyoterapi ve Rehabilitasyon'),
  (237, 'Beslenme ve Diyetetik'),
  (237, 'Hemşirelik'),
  (237, 'Sağlık Yönetimi'),
  (237, 'Ebelik'),
  (238, 'İlahiyat (İngilizce)'),
  (238, 'İlahiyat (Arapça)'),
  (238, 'İlahiyat'),
  (238, 'İlahiyat (İÖ)'),
  (239, 'İşletme (İngilizce)'),
  (239, 'İşletme (Almanca)'),
  (239, 'İşletme Enformatiği (Almanca)'),
  (239, 'İşletme'),
  (239, 'İşletme Yönetimi (İngilizce) (UOLP-ABD North Carolina Üniversitesi (UNCW)) (Ücretli)'),
  (239, 'İşletme (İÖ)'),
  (240, 'Adalet'),
  (241, 'Eczacılık'),
  (242, 'Hukuk'),
  (242, 'Hukuk(İÖ)'),
  (243, 'İngilizce Öğretmenliği (İngilizce)'),
  (243, 'Türk Dili ve Edebiyatı Öğretmenliği'),
  (243, 'Türkçe Öğretmenliği'),
  (243, 'Coğrafya Öğretmenliği'),
  (243, 'Zihin Engelliler Öğretmenliği'),
  (243, 'Rehberlik ve Psikolojik Danışmanlık'),
  (243, 'Tarih Öğretmenliği '),
  (243, 'Matematik Öğretmenliği'),
  (243, 'Zihin Engelliler Öğretmenliği (İÖ)'),
  (243, 'İlköğretim Matematik Öğretmenliği'),
  (243, 'Okul Öncesi Öğretmenliği'),
  (243, 'Fransızca Öğretmenliği (Fransızca) (KKTC Uyruklu)'),
  (243, 'Fransızca Öğretmenliği (Fransızca)'),
  (243, 'Sosyal Bilgiler Öğretmenliği'),
  (243, 'Sınıf Öğretmenliği'),
  (243, 'Kimya Öğretmenliği'),
  (243, 'Bilgisayar ve Öğretim Teknolojileri Öğretmenliği'),
  (243, 'Fen Bilgisi Öğretmenliği'),
  (243, 'Biyoloji Öğretmenliği'),
  (243, 'Fizik Öğretmenliği'),
  (243, 'Almanca Öğretmenliği (Almanca)'),
  (244, 'Mütercim-Tercümanlık (İngilizce)'),
  (244, 'Türk Dili ve Edebiyatı'),
  (244, 'Tarih'),
  (244, 'Coğrafya '),
  (244, 'Sosyoloji (İngilizce)'),
  (244, 'Sanat Tarihi '),
  (244, 'Bilgi ve Belge Yönetimi'),
  (244, 'Matematik'),
  (244, 'Kimya'),
  (244, 'Biyoloji'),
  (244, 'Fizik'),
  (244, 'Alman Dili ve Edebiyatı'),
  (245, 'Elektrik-Elektronik Mühendisliği (İngilizce)'),
  (245, 'Endüstri Mühendisliği (İngilizce)'),
  (245, 'Bilgisayar Mühendisliği (İngilizce)'),
  (245, 'Makine Mühendisliği (İngilizce)'),
  (245, 'Elektrik-Elektronik Mühendisliği'),
  (245, 'Mekatronik Mühendisliği'),
  (245, 'Makine Mühendisliği'),
  (245, 'Kimya Mühendisliği'),
  (245, 'Biyomühendislik (İngilizce)'),
  (245, 'Metalurji ve Malzeme Mühendisliği (İngilizce)'),
  (245, 'Çevre Mühendisliği (İngilizce)'),
  (245, 'Kimya Mühendisliği (KKTC Uyruklu)'),
  (245, 'Mekatronik Mühendisliği (KKTC Uyruklu)'),
  (246, 'İktisat (İngilizce)'),
  (246, 'Maliye'),
  (246, 'İktisat'),
  (246, 'Maliye (İÖ)'),
  (246, 'Çalışma Ekonomisi ve Endüstri İlişkileri '),
  (246, 'İktisat (İÖ)'),
  (246, 'Ekonometri'),
  (246, 'Çalışma Ekonomisi ve Endüstri İlişkileri (İÖ)'),
  (246, 'Ekonometri (İÖ)'),
  (248, 'Elektrik-Elektronik Mühendisliği'),
  (248, 'Mekatronik Mühendisliği'),
  (248, 'Makine Mühendisliği'),
  (248, 'Metalurji ve Malzeme Mühendisliği'),
  (248, 'Elektrik-Elektronik Mühendisliği (M.T.O.K.)'),
  (248, 'Mekatronik Mühendisliği (M.T.O.K.)'),
  (248, 'Makine Mühendisliği (M.T.O.K.)'),
  (248, 'Tekstil Mühendisliği'),
  (248, 'Metalurji ve Malzeme Mühendisliği (M.T.O.K.)'),
  (248, 'Tekstil Mühendisliği (M.T.O.K.)'),
  (248, 'Mekatronik Mühendisliği (KKTC Uyruklu)'),
  (249, 'Aktüerya (KKTC Uyruklu)'),
  (249, 'Bankacılık'),
  (249, 'Sermaye Piyasası'),
  (249, 'Aktüerya'),
  (249, 'Sigortacılık'),
  (249, 'Bankacılık (KKTC Uyruklu)'),
  (249, 'Sigortacılık (KKTC Uyruklu)'),
  (250, 'Takı Tasarımı'),
  (252, 'Basım ve Yayın Teknolojileri'),
  (252, 'Basım ve Yayın Teknolojileri (İÖ)'),
  (252, 'Basım ve Yayın Teknolojileri (KKTC Uyruklu)'),
  (252, 'Bilgisayar Programcılığı'),
  (252, 'Bilgisayar Programcılığı (İÖ)'),
  (252, 'Bilgisayar Programcılığı (Uzaktan Öğretim)'),
  (252, 'Biyomedikal Cihaz Teknolojisi'),
  (252, 'Elektrik'),
  (252, 'Elektrik (İÖ)'),
  (252, 'Elektronik Haberleşme Teknolojisi'),
  (252, 'Elektronik Haberleşme Teknolojisi (İÖ)'),
  (252, 'Elektronik Teknolojisi'),
  (252, 'Elektronik Teknolojisi (İÖ)'),
  (252, 'Giyim Üretim Teknolojisi'),
  (252, 'Giyim Üretim Teknolojisi (İÖ)'),
  (252, 'İşçi Sağlığı ve İş Güvenliği'),
  (252, 'İşçi Sağlığı ve İş Güvenliği (İÖ)'),
  (252, 'İşçi Sağlığı ve İş Güvenliği (Uzaktan Öğretim)'),
  (252, 'Kontrol ve Otomasyon Teknolojisi'),
  (252, 'Makine'),
  (252, 'Makine (İÖ)'),
  (252, 'Moda Tasarımı'),
  (252, 'Moda Tasarımı (İÖ)'),
  (252, 'Moda Tasarımı (Uzaktan Öğretim)'),
  (253, 'Mimarlık'),
  (253, 'Şehir ve Bölge Planlama'),
  (253, 'Şehir ve Bölge Planlama (KKTC Uyruklu)'),
  (254, ' Tıp'),
  (255, 'Fizyoterapi ve Rehabilitasyon'),
  (256, 'Hemşirelik'),
  (257, 'Anestezi'),
  (257, 'İlk ve Acil Yardım'),
  (257, 'Nükleer Tıp Teknikleri'),
  (257, 'Odyometri'),
  (257, 'Radyoterapi'),
  (257, 'Tıbbi Dokümantasyon ve Sekreterlik'),
  (257, 'Tıbbi Görüntüleme Teknikleri'),
  (257, 'Tıbbi Görüntüleme Teknikleri (KKTC Uyruklu)'),
  (257, 'Tıbbi Laboratuvar Teknikleri'),
  (258, 'Elektrik-Elektronik Mühendisliği (İngilizce)'),
  (258, 'Endüstri Mühendisliği'),
  (258, 'Bilgisayar Mühendisliği (İngilizce)'),
  (258, 'İnşaat Mühendisliği'),
  (258, 'Makine Mühendisliği'),
  (258, 'İnşaat Mühendisliği (İÖ)'),
  (258, 'Makine Mühendisliği (İÖ)'),
  (258, 'Bilgisayar Mühendisliği (İngilizce) (KKTC Uyruklu)'),
  (258, 'Metalurji ve Malzeme Mühendisliği'),
  (258, 'Çevre Mühendisliği'),
  (258, 'Tekstil Mühendisliği'),
  (258, 'Jeoloji Mühendisliği'),
  (258, 'Maden Mühendisliği'),
  (258, 'Jeofizik Mühendisliği'),
  (258, 'Jeofizik Mühendisliği (KKTC Uyruklu)'),
  (260, 'Kamu Yönetimi'),
  (260, 'Kamu Yönetimi (İÖ)'),
  (260, 'Yönetim Bilişim Sistemleri'),
  (260, 'İktisat'),
  (260, 'Maliye (İÖ)'),
  (260, 'İşletme'),
  (260, 'Çalışma Ekonomisi ve Endüstri İlişkileri '),
  (260, 'İktisat (KKTC Uyruklu)'),
  (260, 'Ekonometri'),
  (260, 'Çalışma Ekonomisi ve Endüstri İlişkileri (İÖ)'),
  (260, 'İşletme (İÖ)'),
  (260, 'İktisat (İÖ)'),
  (260, 'Ekonometri (İÖ)'),
  (261, 'Hukuk'),
  (262, 'Adalet'),
  (263, 'İngilizce Öğretmenliği (İngilizce)'),
  (263, 'Türk Dili ve Edebiyatı Öğretmenliği'),
  (263, 'Türkçe Öğretmenliği'),
  (263, 'Zihin Engelliler Öğretmenliği'),
  (263, 'Coğrafya Öğretmenliği  '),
  (263, 'Rehberlik ve Psikolojik Danışmanlık'),
  (263, 'Zihin Engelliler Öğretmenliği (İÖ)'),
  (263, 'Tarih Öğretmenliği'),
  (263, 'Matematik Öğretmenliği'),
  (263, 'İlköğretim Matematik Öğretmenliği'),
  (263, 'Okul Öncesi Öğretmenliği'),
  (263, 'Sosyal Bilgiler Öğretmenliği'),
  (263, 'Sınıf Öğretmenliği'),
  (263, 'Okul Öncesi Öğretmenliği (İÖ)'),
  (264, 'Bilgisayar Programcılığı'),
  (264, 'Bilgisayar Programcılığı (İÖ)'),
  (264, 'Bilgisayar Programcılığı (Uzaktan Öğretim)'),
  (264, 'Biyomedikal Cihaz Teknolojisi'),
  (264, 'Biyomedikal Cihaz Teknolojisi (İÖ)'),
  (264, 'Biyomedikal Cihaz Teknolojisi (KKTC Uyruklu)'),
  (264, 'Büro Yönetimi ve Yönetici Asistanlığı'),
  (264, 'Büro Yönetimi ve Yönetici Asistanlığı (İÖ)'),
  (264, 'Döküm'),
  (264, 'Döküm (İÖ)'),
  (264, 'Elektrik'),
  (264, 'Elektrik (İÖ)'),
  (264, 'Elektronik Haberleşme Teknolojisi'),
  (264, 'Elektronik Haberleşme Teknolojisi (İÖ)'),
  (264, 'Elektronik Teknolojisi'),
  (264, 'Elektronik Teknolojisi (İÖ)'),
  (264, 'Harita ve Kadastro'),
  (264, 'Harita ve Kadastro (İÖ)'),
  (264, 'İklimlendirme ve Soğutma Teknolojisi'),
  (264, 'İklimlendirme ve Soğutma Teknolojisi (İÖ)'),
  (264, 'İnşaat Teknolojisi '),
  (264, 'İnşaat Teknolojisi (İÖ)'),
  (264, 'Kimya Teknolojisi'),
  (264, 'Kimya Teknolojisi (İÖ) '),
  (264, 'Kuyumculuk ve Takı Tasarımı'),
  (264, 'Kuyumculuk ve Takı Tasarımı (İÖ)'),
  (264, 'Makine'),
  (264, 'Makine (İÖ)'),
  (264, 'Makine, Resim ve Konstrüksiyon'),
  (264, 'Makine, Resim ve Konstrüksiyon (İÖ)'),
  (264, 'Mekatronik'),
  (264, 'Mekatronik (İÖ)'),
  (264, 'Muhasebe ve Vergi Uygulamaları'),
  (264, 'Muhasebe ve Vergi Uygulamaları (İÖ)'),
  (264, 'Pazarlama'),
  (264, 'Pazarlama (İÖ)'),
  (264, 'Sağlık Kurumları İşletmeciliği'),
  (264, 'Tarımsal İşletmecilik'),
  (264, 'Tarımsal İşletmecilik (İÖ)'),
  (264, 'Tekstil Teknolojisi'),
  (264, 'Turizm ve Otel İşletmeciliği'),
  (264, 'Turizm ve Otel İşletmeciliği (İÖ)'),
  (264, 'Yapı Tesisat Teknolojisi'),
  (264, 'Yapı Tesisat Teknolojisi (İÖ)'),
  (264, 'Yerel Yönetimler'),
  (264, 'Yerel Yönetimler (İÖ)'),
  (265, 'Matematik (İngilizce)'),
  (265, 'Matematik (İngilizce) (KKTC Uyruklu)'),
  (265, 'Bilgisayar Bilimleri'),
  (265, 'İstatistik'),
  (265, 'Kimya'),
  (265, 'Fizik'),
  (266, 'Mütercim-Tercümanlık (İngilizce)v'),
  (266, 'Psikoloji'),
  (266, 'Amerikan Kültürü ve Edebiyatı (İngilizce)'),
  (266, 'Türk Dili ve Edebiyatı'),
  (266, 'Dilbilim'),
  (266, 'Tarih'),
  (266, 'Sosyoloji'),
  (266, 'Karşılaştırmalı Edebiyat'),
  (266, 'Tarih (İÖ)'),
  (266, 'Sosyoloji (İÖ)'),
  (266, 'Felsefe'),
  (266, 'Müzecilik'),
  (266, 'Felsefe (KKTC Uyruklu)'),
  (266, 'Arkeoloji'),
  (266, 'Arkeoloji (İÖ)'),
  (267, 'Uluslararası İlişkiler (İngilizce)'),
  (267, 'İşletme (İngilizce)'),
  (267, 'Uluslararası İşletmecilik ve Ticaret (İngilizce)'),
  (267, 'İktisat (İngilizce)'),
  (267, 'Turizm İşletmeciliği (İngilizce)'),
  (267, 'İktisat (İngilizce) (UOLP-New York Eyalet Üniversitesi (SUNY Albany)) (Ücretli)'),
  (267, ' İşletme (İngilizce) (UOLP-New York Eyalet Üniversitesi (SUNY Albany)) (Ücretli)'),
  (267, 'Uluslararası İlişkiler (İngilizce) (UOLP-New York Eyalet Üniversitesi (SUNY Albany)) (Ücretli)'),
  (268, 'Elektrik-Elektronik Mühendisliği (İngilizce)'),
  (268, 'Endüstri Mühendisliği'),
  (268, 'Bilgisayar Mühendisliği (İngilizce)'),
  (268, 'İnşaat Mühendisliği'),
  (268, 'Makine Mühendisliği'),
  (268, 'İnşaat Mühendisliği (İÖ)'),
  (268, 'Makine Mühendisliği (İÖ)'),
  (268, 'Bilgisayar Mühendisliği (İngilizce) (KKTC Uyruklu)'),
  (268, 'Metalurji ve Malzeme Mühendisliği'),
  (268, 'Çevre Mühendisliği'),
  (268, 'Tekstil Mühendisliği'),
  (268, 'Jeoloji Mühendisliği'),
  (268, 'Maden Mühendisliği'),
  (268, 'Jeofizik Mühendisliği'),
  (268, 'Jeofizik Mühendisliği (KKTC Uyruklu)'),
  (269, 'İlahiyat'),
  (269, 'İlahiyat (İÖ)'),
  (270, 'Film Tasarım ve Yönetmenliği'),
  (270, 'Film Tasarım ve Yazarlık'),
  (270, 'Canlandırma Filmi Tasarım ve Yönetimi'),
  (270, 'Kurgu-Ses ve Görüntü Yönetimi'),
  (272, 'Doğal Yapı Taşları Teknolojisi'),
  (272, 'Endüstriyel Cam ve Seramik'),
  (272, 'Geoteknik'),
  (272, 'Sondaj Teknolojisi'),
  (274, 'Denizcilik İşletmeleri Yönetimi (İngilizce)'),
  (274, 'Lojistik Yönetimi (İngilizce)'),
  (274, 'Gemi Makineleri İşletme Mühendisliği (İngilizce)'),
  (274, 'Deniz Ulaştırma İşletme Mühendisliği (İngilizce)'),
  (274, ' Denizcilik İşletmeleri Yönetimi (İngilizce) (UOLP-Maine Maritime Academy) (Ücretli)'),
  (274, 'Deniz Ulaştırma İşletme Mühendisliği (İngilizce) (UOLP-Maine Maritime'),
  (274, 'Gemi Makineleri İşletme Mühendisliği (İngilizce) (UOLP-Maine Maritime'),
  (275, 'Mimari Restorasyon'),
  (276, 'Matematik Mühendisliği (İngilizce)'),
  (276, 'Kimya Mühendisliği (İngilizce)'),
  (276, 'Matematik Mühendisliği'),
  (276, 'Metalurji ve Malzeme Mühendisliği (İngilizce)'),
  (276, 'Kimya Mühendisliği'),
  (276, 'Biyomühendislik (İngilizce)'),
  (276, 'Gıda Mühendisliği'),
  (276, 'Biyomühendislik'),
  (276, 'Metalurji ve Malzeme Mühendisliği'),
  (276, 'Kimya Mühendisliği (KKTC Uyruklu)'),
  (277, 'Moleküler Biyoloji ve Genetik'),
  (277, 'Türk Dili ve Edebiyatı'),
  (277, 'Kimya (İngilizce)'),
  (277, 'Matematik'),
  (277, 'Kimya'),
  (277, 'İstatistik'),
  (277, 'Fizik'),
  (277, 'Mütercim-Tercümanlık (Fransızca)'),
  (277, 'Matematik (KKTC Uyruklu)'),
  (279, 'İnşaat Mühendisliği (İngilizce)  '),
  (279, 'İnşaat Mühendisliği'),
  (279, 'Harita Mühendisliği'),
  (279, 'Çevre Mühendisliği'),
  (279, 'Harita Mühendisliği (KKTC Uyruklu)'),
  (280, 'Bilgisayar Mühendisliği  '),
  (280, 'Elektronik ve Haberleşme Mühendisliği'),
  (280, 'Elektrik Mühendisliği'),
  (280, 'Kontrol ve Otomasyon Mühendisliği (İngilizce)'),
  (280, 'Kontrol ve Otomasyon Mühendisliği'),
  (280, 'Elektronik ve Haberleşme Mühendisliği (KKTC Uyruklu)'),
  (281, 'İngilizce Öğretmenliği'),
  (281, 'Türkçe Öğretmenliği'),
  (281, 'Rehberlik ve Psikolojik Danışmanlık'),
  (281, 'Okul Öncesi Öğretmenliği'),
  (281, 'İlköğretim Matematik Öğretmenliği'),
  (281, 'Sosyal Bilgiler Öğretmenliği'),
  (281, 'Sınıf Öğretmenliği'),
  (281, 'Bilgisayar ve Öğretim Teknolojileri Öğretmenliği'),
  (281, ' Fen Bilgisi Öğretmenliği'),
  (282, 'İletişim Tasarımı'),
  (282, 'Sanat Yönetimi'),
  (283, 'Endüstri Mühendisliği (İngilizce)'),
  (283, 'Endüstri Mühendisliği'),
  (283, 'Mekatronik Mühendisliği (İngilizce)'),
  (283, 'Mekatronik Mühendisliği'),
  (283, 'Makine Mühendisliği'),
  (284, 'Mimarlık (İngilizce)'),
  (284, 'Mimarlık'),
  (284, 'Şehir ve Bölge Planlama'),
  (285, 'İktisat (İngilizce)'),
  (285, 'Siyaset Bilimi ve Uluslararası İlişkiler'),
  (285, 'İşletme'),
  (285, 'İktisat'),
  (285, 'Siyaset Bilimi ve Uluslararası İlişkiler (KKTC Uyruklu)'),
  (286, 'Gemi İnşaatı ve Gemi Makineleri Mühendisliği'),
  (286, 'Gemi Makineleri İşletme Mühendisliği'),
  (287, NULL);